lib/spotify_wall_web/router.ex
defmodule SpotifyWallWeb.Router do
  use SpotifyWallWeb, :router

  import Plug.BasicAuth
  import Phoenix.LiveDashboard.Router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, {SpotifyWallWeb.LayoutView, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug SpotifyWallWeb.Auth
  end

  pipeline :public do
    plug :put_root_layout, {SpotifyWallWeb.LayoutView, :public_root}
    plug SpotifyWallWeb.RedirectSignedIn
  end

  pipeline :admin do
    unless Mix.env() == :dev do
      plug :basic_auth, Application.compile_env(:spotify_wall, :admin_area)
    end
  end

  scope "/auth", SpotifyWallWeb do
    pipe_through :browser

    get "/:provider", AccountConnectionController, :request
    get "/:provider/callback", AccountConnectionController, :callback
    post "/:provider/callback", AccountConnectionController, :callback
  end

  scope "/", SpotifyWallWeb do
    pipe_through [:browser, :public]
    get "/", PublicController, :index
  end

  scope "/", SpotifyWallWeb do
    pipe_through :browser

    get "/join/:id", JoinController, :show

    # TODO: Better wording here than accept?
    put "/join/:id/accept", JoinController, :accept
    # NOTE: We have to support get here since spotify will call this after the user has signed in.
    get "/join/:id/accept", JoinController, :accept
  end

  scope "/", SpotifyWallWeb do
    pipe_through [:browser, :authenticate_user]

    resources "/walls", WallController, except: [:show] do
      delete "/members/:id", MembershipController, :delete
      put "/pause", MembershipController, :pause
      put "/resume", MembershipController, :resume

      delete "/leave", MembershipController, :leave
      put "/revoke_join", MembershipController, :revoke_join_link
    end

    live "/walls/:id/", WallLive
  end

  scope "/account", SpotifyWallWeb do
    pipe_through [:browser, :authenticate_user]

    get "/", AccountConnectionController, :show
    delete "/", AccountConnectionController, :delete
  end

  scope "/session", SpotifyWallWeb do
    pipe_through [:browser, :authenticate_user]

    delete "/", SessionController, :delete
  end

  scope "/" do
    pipe_through [:browser, :admin]

    live_dashboard "/dashboard",
      metrics: SpotifyWallWeb.Telemetry,
      additional_pages: [
        spotify_sessions: SpotifyWallWeb.LiveDashboard.SpotifySessionsPage,
        users: SpotifyWallWeb.LiveDashboard.UsersPage
      ],
      ecto_repos: [SpotifyWall.Repo]
  end
end

lib/spotify_wall_web/views/layout_view.ex
defmodule SpotifyWallWeb.LayoutView do
  use SpotifyWallWeb, :view
end

lib/spotify_wall_web/templates/layout/app.html.eex
<%= @inner_content %>

lib/spotify_wall_web/templates/layout/live.html.leex
<%= if live_flash(@flash, :info) do %>
  <div class="rounded-md bg-blue-50 p-4">
    <div class="flex">
      <div class="flex-shrink-0">
        <svg class="h-5 w-5 text-blue-400" viewBox="0 0 20 20" fill="currentColor">
          <path fill-rule="evenodd" d="M18 10a8 8 0 11-16 0 8 8 0 0116 0zm-7-4a1 1 0 11-2 0 1 1 0 012 0zM9 9a1 1 0 000 2v3a1 1 0 001 1h1a1 1 0 100-2v-3a1 1 0 00-1-1H9z" clip-rule="evenodd" />
        </svg>
      </div>
      <div class="ml-3 flex-1 md:flex md:justify-between">
        <p class="text-sm leading-5 text-blue-700" phx-value-key="info" phx-click="lv:clear-flash">
          <%= live_flash(@flash, :info) %>
        </p>
      </div>
    </div>
  </div>
<% end %>

<%= @inner_content %>

lib/spotify_wall_web/templates/layout/public_root.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <%= csrf_meta_tag() %>
    <link phx-track-static rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>"/>
    <script src="https://cdn.jsdelivr.net/npm/clipboard@2.0.6/dist/clipboard.min.js"></script>
    <script defer phx-track-static type="text/javascript" src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
  </head>
  <body>
    <%= @inner_content %>
  </body>
</html>

lib/spotify_wall_web/templates/layout/root.html.leex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <%= csrf_meta_tag() %>
    <%= live_title_tag assigns[:page_title] || "SpotifyWall" %>
    <link phx-track-static rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>"/>
    <script src="https://cdn.jsdelivr.net/npm/clipboard@2.0.6/dist/clipboard.min.js"></script>
    <script defer phx-track-static type="text/javascript" src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
  </head>
  <body>
    <div class="h-screen">
      <div class="mx-auto py-12 px-4 max-w-screen-xl sm:px-6 lg:px-8 lg:py-24 h-screen">
        <div class="space-y-12">
          <div class="md:flex md:items-center md:justify-between">
            <div class="flex-1 min-w-0">
              <h2 class="text-3xl font-bold leading-7 text-white sm:text-3xl sm:leading-9 sm:truncate">
                <%= link "Spotify Wall", to: Routes.wall_path(@conn, :index) %>
              </h2>
            </div>
            <div class="mt-4 flex md:mt-0 md:ml-4">
              <span class="inline-flex">
                <%= if @current_user do %>
                  <span class="relative z-0 inline-flex space-x-4">
                    <%= button("Dashboard", to: Routes.wall_path(@conn, :index), method: :get, class: "ml-px relative inline-flex items-center px-3 py-2 rounded-md border border-transparent text-white bg-gray-600 hover:bg-gray-500 active:bg-gray-700 text-sm leading-5 font-medium focus:z-10 focus:outline-none focus:border-blue-300 focus:shadow-outline-blue transition ease-in-out duration-150") %>
                    <%= button("Log out", to: Routes.session_path(@conn, :delete), method: :delete, class: "ml-px relative inline-flex items-center px-3 py-2 rounded-md border border-transparent text-white bg-gray-600 hover:bg-gray-500 active:bg-gray-700 text-sm leading-5 font-medium focus:z-10 focus:outline-none focus:border-blue-300 focus:shadow-outline-blue transition ease-in-out duration-150") %>
                  </span>
                <% else %>
                  <%= button("Sign in", to: "/auth/spotify", method: :get, class: "inline-flex items-center px-4 py-2 border border-transparent text-sm leading-5 font-medium rounded-md text-white bg-gray-600 hover:bg-gray-500 focus:outline-none focus:shadow-outline-gray focus:border-gray-700 active:bg-gray-700 transition duration-150 ease-in-out") %>
                <% end %>
              </span>
            </div>
          </div>
          <%= @inner_content %>
        </div>
      </div>
    </div>
  </body>
</html>